version: "3"

tasks:
  go:run:
    desc: Run code
    cmds:
      - go run ./

  goreleaser:check:
    desc: Validate configuration
    cmds:
      - goreleaser check

  goreleaser:release:dry:
    desc: "Build packages"
    cmds:
      - goreleaser release --snapshot --clean

  goreleaser:build:
    desc: Build code
    cmds:
      - task: goreleaser:release:dry
      - cp ./dist/clockify-to-jira_darwin_all/clockify-to-jira ./

  goreleaser:release:
    desc: "Build packages and release"
    cmds:
      - goreleaser --clean

  git:tag:patch:
    desc: Create semver patch tag (v0.0.1)
    cmds:
      - git semver patch

  git:tag:minor:
    desc: Create semver minor tag (v0.1.0)
    cmds:
      - git semver minor

  git:tag:major:
    desc: Create semver minor tag (v1.0.0)
    cmds:
      - git semver major

  git:push:
    desc: Push to repo
    cmds:
      - git push origin main --tags

  semver:install:
    desc: Install semver plugin https://github.com/markchalloner/git-semver
    cmds:
      - (git clone https://github.com/markchalloner/git-semver.git && sudo git-semver/install.sh)
