# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  go:run:
    desc: Run code
    cmds:
      - go run ./ {{.CLI_ARGS}}

  go:test:
    desc: Test all packages
    cmds:
      - go test ./... -count=1 -cover -ldflags "{{.LDFLAGS | join " "}}" | grep -v -E 'github.com/kruc/clockify-to-jira/internal/({{.SKIP_PACKAGES | join "|"}})'
    vars:
      LDFLAGS:
        - -X 'github.com/kruc/clockify-to-jira/internal/version.BuildVersion=v1.2.3'
        - -X 'github.com/kruc/clockify-to-jira/internal/version.GitCommit=3dfbf35'
        - -X 'github.com/kruc/clockify-to-jira/internal/version.BuildDate=08.10.2022 09:19:08'
      SKIP_PACKAGES:
        - assert

  goreleaser:check:
    desc: Validate configuration
    cmds:
      - goreleaser check

  goreleaser:release:dry:
    desc: "Build packages"
    cmds:
      - goreleaser release --snapshot --clean

  goreleaser:build:
    desc: Build code
    cmds:
      - task: goreleaser:release:dry
      - cp ./dist/clockify-to-jira_darwin_all/clockify-to-jira ./

  goreleaser:release:
    desc: "Build packages and release"
    cmds:
      - goreleaser --clean

  git:tag:patch:
    desc: Create semver patch tag (v0.0.1)
    cmds:
      - git semver patch

  git:tag:minor:
    desc: Create semver minor tag (v0.1.0)
    cmds:
      - git semver minor

  git:tag:major:
    desc: Create semver major tag (v1.0.0)
    cmds:
      - git semver major

  git:push:
    desc: Push to repo
    cmds:
      - git push origin main --tags

  semver:install:
    desc: Install semver plugin https://github.com/markchalloner/git-semver
    cmds:
      - (git clone https://github.com/markchalloner/git-semver.git && sudo git-semver/install.sh)
    status:
      - test -d git-semver
