version: '2'

tasks:
  run:
    desc: Run code
    cmds:
      - go run ./
    silent: true

  compile:
    cmds:
      - goreleaser --snapshot --skip-publish --rm-dist

  build:
    desc: Build code
    cmds:
      - task: compile
      - cp ./dist/clockify-to-jira_darwin_amd64/clockify-to-jira ./

  install:
    desc: Install code
    cmds:
      - task: compile
      - cp ./dist/clockify-to-jira_darwin_amd64/clockify-to-jira $GOPATH/bin/clockify-to-jira

  dry-release:
    desc: "Build packages"
    cmds:
      - goreleaser --snapshot --skip-publish --rm-dist
    silent: true

  release:
    desc: "Build packages and release"
    cmds:
      - goreleaser --rm-dist
    silent: true

  git:tag:patch:
    desc: Create semver patch tag (v0.0.1)
    cmds:
      - git semver patch
    silent: true

  git:tag:minor:
    desc: Create semver minor tag (v0.1.0)
    cmds:
      - git semver minor
    silent: true

  git:tag:major:
    desc: Create semver minor tag (v1.0.0)
    cmds:
      - git semver major
    silent: true

  git:push:
    desc: Push to repo
    cmds:
      - git push origin master --tags
