name: Coverage

on:
  pull_request:
    branches:
      - "main"

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Check goreleaser config
        run: goreleaser check

      - name: Goreleaser dry run release
        run: goreleaser release --snapshot --clean

      - name: Run unit tests
        run: task go:test:ci

      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.4
        with:
          github-token: ${{ secrets.github_token }}
          file: coverage.out
          format: golang
