name: Coverage

on:
  pull_request:
    branches:
      - "main"

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true

      - name: Prepare app config
        run: mkdir -p /home/runner/.clockify-to-jira/; cp ./internal/config/ci-config.yaml /home/runner/.clockify-to-jira/config.yaml

      - name: Check goreleaser config
        run: goreleaser check

      - name: Goreleaser dry run release
        run: goreleaser release --snapshot --clean

      - name: Calc coverage
        run: go test -v -covermode=count -coverprofile=coverage.out

      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.1.1

      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.4
        with:
          github-token: ${{ secrets.github_token }}
          file: coverage.lcov
